service: ${file(./package.json):name}

custom: ${file(./config.js):buckets}

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${self:custom.eventsBucket}
            - "/*"

functions:
  publish:
    handler: handlers/publisher.publish
    environment:
      TZ: Europe/Belfast
    events:
      - existingS3:
          bucket: ${self:custom.eventsBucket}
          events:
            - s3:ObjectCreated:*


resources:
  Resources:
    MuxerTransformedEventsS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.eventsBucket}


plugins:
  - serverless-plugin-existing-s3
